In [1]:
#Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [7]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[4,20],
            [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 20],
       [ 3,  4]])>

In [8]:
matrix.ndim

2

In [10]:
anaother_matrix = tf.constant([[1,2,3],
             [2,3,4],
             [4,5,6]])
anaother_matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])>

In [11]:
anaother_matrix.ndim

2

In [12]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
              [3,4,5]],
              [[6,7,8],
               [2,3,4]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[6, 7, 8],
        [2, 3, 4]]])>

In [13]:
tensor.ndim

3

what we have created so far:

* Scalar: a single number
* Vector: a number with direction(e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.variable`

In [15]:
# Create the same tensor with tf.variable() as above
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,5])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5])>)

In [16]:
# Let's try change one of the elements in our changable_tensor
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [17]:
# Let's try change one of the elements in our unchangable_tensor
unchangable_tensor[0].assign(7)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers

In [21]:
# Create two random (but the same) tensors 
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)